name: Flipper_Teste
description: Projeto para teste da vaga de Desenvolvedor Flutter

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  provider: ^5.0.0
  graphql: ^5.0.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5

flutter:
  assets:
    - .env
  uses-material-design: true
  fonts:
    - family: Milliard
      fonts:
        - asset: fonts/Milliard_Medium.otf
        - asset: fonts/Milliard_Bold.otf
          weight: 500
        - asset: fonts/Milliard_ExtraBold.otf
          weight: 700